In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)

In [3]:
import os

In [5]:
path = os.getcwd()
print(f"current path: {path}")

current path: c:\Users\alvar\repos\GitHub\GenderStudy

In [6]:
dst_path = os.path.join(path, "data_dst")

In [10]:
df_matriculados_T = pd.read_csv(os.path.join(dst_path, "matriculados_T_STEM.csv"))
df_graduados_T = pd.read_csv(os.path.join(dst_path, "graduados_T_STEM.csv"))
df_matriculados_stats = pd.read_csv(os.path.join(dst_path, "matriculados_T_STEM_stats.csv"))
df_graduados_stats = pd.read_csv(os.path.join(dst_path, "graduados_T_STEM_stats.csv"))

In [11]:
df_matriculados_T.head()

,Curso,Titulacion,Total,Mujeres,Hombres,Porcentaje_Mujeres,Porcentaje_Hombres
0,21-22,INGENIERÍA BIOMÉDICA,65,36,29,55.38,44.62
1,21-22,INGENIERÍA EN SONIDO E IMAGEN EN TELECOMUNICACIÓN,75,21,54,28.00,72.00
2,21-22,INGENIERÍA INFORMÁTICA,210,25,185,11.90,88.10
3,21-22,INGENIERÍA MULTIMEDIA,98,14,84,14.29,85.71
4,21-22,INGENIERÍA ROBÓTICA,67,11,56,16.42,83.58

In [12]:
df_graduados_T.head()

,Curso,Titulacion,Total,Mujeres,Hombres,Porcentaje_Mujeres,Porcentaje_Hombres
0,21-22,INGENIERÍA BIOMÉDICA,25,15,10,60.00,40.00
1,21-22,INGENIERÍA EN SONIDO E IMAGEN EN TELECOMUNICACIÓN,26,4,22,15.38,84.62
2,21-22,INGENIERÍA INFORMÁTICA,109,12,97,11.01,88.99
3,21-22,INGENIERÍA MULTIMEDIA,64,15,49,23.44,76.56
4,21-22,INGENIERÍA ROBÓTICA,48,9,39,18.75,81.25

In [20]:
df_matriculados_stats[["Titulacion", "Media_Porcentaje_Mujeres", "Media_Porcentaje_Hombres"]].sort_values(by="Media_Porcentaje_Mujeres",ascending=True)

,Titulacion,Media_Porcentaje_Mujeres,Media_Porcentaje_Hombres
3,INGENIERÍA INFORMÁTICA,15.43,84.57
1,INGENIERÍA EN INTELIGENCIA ARTIFICIAL,17.18,82.82
5,INGENIERÍA ROBÓTICA,20.70,79.30
4,INGENIERÍA MULTIMEDIA,23.86,76.14
2,INGENIERÍA EN SONIDO E IMAGEN EN TELECOMUNICACIÓN,24.87,75.13
0,INGENIERÍA BIOMÉDICA,57.01,42.99

In [22]:
df_graduados_stats[["Titulacion", "Media_Porcentaje_Mujeres", "Media_Porcentaje_Hombres"]].sort_values(by="Media_Porcentaje_Mujeres",ascending=True)

,Titulacion,Media_Porcentaje_Mujeres,Media_Porcentaje_Hombres
2,INGENIERÍA INFORMÁTICA,11.40,88.60
1,INGENIERÍA EN SONIDO E IMAGEN EN TELECOMUNICACIÓN,23.40,76.60
3,INGENIERÍA MULTIMEDIA,23.59,76.41
4,INGENIERÍA ROBÓTICA,23.70,76.30
0,INGENIERÍA BIOMÉDICA,54.94,45.06

In [23]:
df_diferencia = pd.merge(
    df_matriculados_stats[
        ["Titulacion", "Media_Porcentaje_Mujeres"]
    ],
    df_graduados_stats[
        ["Titulacion", "Media_Porcentaje_Mujeres"]
    ],
    on="Titulacion",
    how="inner",
    suffixes=("_Matriculadas", "_Graduadas")
)

df_diferencia["Diferencia_Mujeres_pp"] = (
    df_diferencia["Media_Porcentaje_Mujeres_Graduadas"]
    - df_diferencia["Media_Porcentaje_Mujeres_Matriculadas"]
).round(2)

df_diferencia.sort_values("Diferencia_Mujeres_pp")

,Titulacion,Media_Porcentaje_Mujeres_Matriculadas,Media_Porcentaje_Mujeres_Graduadas,Diferencia_Mujeres_pp
2,INGENIERÍA INFORMÁTICA,15.43,11.40,-4.03
0,INGENIERÍA BIOMÉDICA,57.01,54.94,-2.07
1,INGENIERÍA EN SONIDO E IMAGEN EN TELECOMUNICACIÓN,24.87,23.40,-1.47
3,INGENIERÍA MULTIMEDIA,23.86,23.59,-0.27
4,INGENIERÍA ROBÓTICA,20.70,23.70,3.00